from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "05_EXECUCAO" / "141_SAFE_APPLY_V2"
REPORT = OUT / "SAFE_APPLY_V2.md"
STATE = OUT / "SAFE_APPLY_V2.json"

GENERATED_FILE = REPO / "11_SCRIPTS" / "jarvis_generated_patch_notes.py"
GENERATED_REL = "11_SCRIPTS/jarvis_generated_patch_notes.py"

ALLOWED_REAL_WRITE_PATHS = {
    GENERATED_REL,
}

BLOCKED_PATTERNS = [
    r"api[_-]?key",
    r"secret",
    r"token",
    r"password",
    r"credential",
    r"\.env",
    r"service_role",
    r"private[_-]?key",
]

MAX_PATCH_BYTES = 12000


def run(cmd: list[str]) -> tuple[int, str]:
    result = subprocess.run(cmd, cwd=REPO, text=True, capture_output=True, check=False)
    return result.returncode, (result.stdout + result.stderr).strip()


def git_status() -> str:
    _, out = run(["git", "status", "-sb"])
    return out


def git_porcelain() -> str:
    _, out = run(["git", "status", "--porcelain"])
    return out


def is_clean() -> bool:
    return git_porcelain().strip() == ""


def scan_blocked(text: str) -> list[str]:
    hits = []
    for pattern in BLOCKED_PATTERNS:
        if re.search(pattern, text, flags=re.IGNORECASE):
            hits.append(pattern)
    return hits


def build_generated_content(goal: str) -> str:
    now = datetime.now().isoformat(timespec="seconds")

    note = {
        "generated_at": now,
        "goal": goal,
        "source": "jarvis_safe_apply_v2",
        "mode": "safe_generated_patch",
        "tracked_real_write": True,
        "allowed_path": GENERATED_REL,
        "rules": [
            "only generated file writes are allowed in v2",
            "run py_compile before commit",
            "keep git status clean after commit",
            "do not store sensitive values",
        ],
    }

    return (
        '"""Generated by Jarvis Safe Apply v2.\n'
        "This file is intentionally safe and contains no sensitive values.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"SAFE_APPLY_V2_NOTE = {json.dumps(note, ensure_ascii=False, indent=2)}\n\n"
        "def get_safe_apply_v2_note() -> dict:\n"
        "    return dict(SAFE_APPLY_V2_NOTE)\n"
    )


def base_plan(goal: str, allow_bootstrap_dirty: bool = False) -> dict:
    content = build_generated_content(goal)
    blocked_hits = scan_blocked(content)
    patch_bytes = len(content.encode("utf-8"))

    blockers = []

    if GENERATED_REL not in ALLOWED_REAL_WRITE_PATHS:
        blockers.append(f"Path not allowlisted: {GENERATED_REL}")

    if blocked_hits:
        blockers.append(f"Blocked sensitive pattern(s): {blocked_hits}")

    if patch_bytes > MAX_PATCH_BYTES:
        blockers.append(f"Patch too large: {patch_bytes} bytes")

    clean = is_clean()
    if not clean and not allow_bootstrap_dirty:
        blockers.append("Git working tree is not clean.")

    return {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "goal": goal,
        "mode": "safe_apply_v2",
        "target_file": GENERATED_REL,
        "patch_bytes": patch_bytes,
        "blocked_hits": blocked_hits,
        "allow_bootstrap_dirty": allow_bootstrap_dirty,
        "git_clean_before": clean,
        "blockers": blockers,
        "can_write_real_file": len(blockers) == 0,
        "validations": [
            f"py -3 -m py_compile {GENERATED_REL}",
            "py -3 -m py_compile 11_SCRIPTS\\jarvis_ops.py",
            "git status -sb",
        ],
        "git_status": git_status(),
    }


def write_report(payload: dict) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    STATE.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        "# JARVIS Safe Apply v2 — Block 141",
        "",
        f"Generated at: `{payload['created_at']}`",
        f"Goal: `{payload['goal']}`",
        f"Mode: `{payload['mode']}`",
        f"Target file: `{payload['target_file']}`",
        f"Can write real file: `{payload['can_write_real_file']}`",
        "",
        "## Blockers",
        "",
    ]

    if payload["blockers"]:
        for item in payload["blockers"]:
            lines.append(f"- {item}")
    else:
        lines.append("- No blockers.")

    lines += [
        "",
        "## Validations",
        "",
        "```powershell",
        "\n".join(payload["validations"]),
        "```",
        "",
        "## Git status",
        "",
        "```text",
        payload["git_status"] or "-",
        "```",
        "",
    ]

    if "validation_output" in payload:
        lines += [
            "## Validation output",
            "",
            "```text",
            payload["validation_output"],
            "```",
            "",
        ]

    REPORT.write_text("\n".join(lines), encoding="utf-8")


def prepare(goal: str, allow_bootstrap_dirty: bool) -> int:
    payload = base_plan(goal, allow_bootstrap_dirty)
    write_report(payload)

    print("SAFE_APPLY_V2_PREPARE_DONE")
    print(REPORT)
    print(json.dumps({
        "can_write_real_file": payload["can_write_real_file"],
        "target_file": payload["target_file"],
        "blockers": payload["blockers"],
        "git_status": payload["git_status"],
    }, ensure_ascii=False, indent=2))

    return 0 if payload["can_write_real_file"] or allow_bootstrap_dirty else 1


def check(goal: str, allow_bootstrap_dirty: bool) -> int:
    payload = base_plan(goal, allow_bootstrap_dirty)
    write_report(payload)

    print("SAFE_APPLY_V2_CHECK_DONE")
    print(REPORT)
    print(json.dumps({
        "can_write_real_file": payload["can_write_real_file"],
        "blockers": payload["blockers"],
        "patch_bytes": payload["patch_bytes"],
        "git_status": payload["git_status"],
    }, ensure_ascii=False, indent=2))

    return 0 if payload["can_write_real_file"] else 1


def apply_generated(goal: str, allow_bootstrap_dirty: bool) -> int:
    payload = base_plan(goal, allow_bootstrap_dirty)

    if payload["blockers"]:
        write_report(payload)
        print("SAFE_APPLY_V2_BLOCKED")
        print(REPORT)
        print(json.dumps({
            "blockers": payload["blockers"],
            "git_status": payload["git_status"],
        }, ensure_ascii=False, indent=2))
        return 1

    content = build_generated_content(goal)
    GENERATED_FILE.write_text(content, encoding="utf-8")

    code1, out1 = run(["py", "-3", "-m", "py_compile", GENERATED_REL])
    code2, out2 = run(["py", "-3", "-m", "py_compile", "11_SCRIPTS\\jarvis_ops.py"])

    payload["applied"] = True
    payload["validation_exit_codes"] = {
        "generated_py_compile": code1,
        "ops_py_compile": code2,
    }
    payload["validation_output"] = "\n".join([out1, out2]).strip() or "OK"
    payload["git_status_after"] = git_status()

    write_report(payload)

    print("SAFE_APPLY_V2_APPLY_DONE")
    print(REPORT)
    print(json.dumps({
        "applied": True,
        "target_file": GENERATED_REL,
        "validation_exit_codes": payload["validation_exit_codes"],
        "git_status_after": payload["git_status_after"],
    }, ensure_ascii=False, indent=2))

    return 0 if code1 == 0 and code2 == 0 else 1


def validate(goal: str) -> int:
    payload = base_plan(goal, allow_bootstrap_dirty=True)

    codes = []
    outputs = []

    if GENERATED_FILE.exists():
        c, o = run(["py", "-3", "-m", "py_compile", GENERATED_REL])
        codes.append(c)
        outputs.append(o)

    c, o = run(["py", "-3", "-m", "py_compile", "11_SCRIPTS\\jarvis_safe_apply_v2.py"])
    codes.append(c)
    outputs.append(o)

    c, o = run(["py", "-3", "-m", "py_compile", "11_SCRIPTS\\jarvis_ops.py"])
    codes.append(c)
    outputs.append(o)

    payload["validation_exit_codes"] = codes
    payload["validation_output"] = "\n".join([x for x in outputs if x]).strip() or "OK"
    payload["git_status_after"] = git_status()

    write_report(payload)

    print("SAFE_APPLY_V2_VALIDATE_DONE")
    print(REPORT)
    print(json.dumps({
        "ok": all(code == 0 for code in codes),
        "codes": codes,
        "git_status_after": payload["git_status_after"],
    }, ensure_ascii=False, indent=2))

    return 0 if all(code == 0 for code in codes) else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="JARVIS Block 141 Safe Apply v2")
    parser.add_argument("action", choices=["prepare", "check", "apply-generated", "validate"])
    parser.add_argument("goal", nargs="*", default=["melhorar autonomia do Jarvis"])
    parser.add_argument("--allow-bootstrap-dirty", action="store_true")
    args = parser.parse_args()

    goal = " ".join(args.goal).strip() or "melhorar autonomia do Jarvis"

    if args.action == "prepare":
        return prepare(goal, args.allow_bootstrap_dirty)

    if args.action == "check":
        return check(goal, args.allow_bootstrap_dirty)

    if args.action == "apply-generated":
        return apply_generated(goal, args.allow_bootstrap_dirty)

    if args.action == "validate":
        return validate(goal)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
