"""Generated by Jarvis Safe Apply v2.
This file is intentionally safe and contains no sensitive values.
"""

from __future__ import annotations

SAFE_APPLY_V2_NOTE = {
  "generated_at": "2026-06-03T11:14:15",
  "goal": "gerar patch seguro controlado",
  "source": "jarvis_safe_apply_v2",
  "mode": "safe_generated_patch",
  "tracked_real_write": true,
  "allowed_path": "11_SCRIPTS/jarvis_generated_patch_notes.py",
  "rules": [
    "only generated file writes are allowed in v2",
    "run py_compile before commit",
    "keep git status clean after commit",
    "do not store sensitive values"
  ]
}

def get_safe_apply_v2_note() -> dict:
    return dict(SAFE_APPLY_V2_NOTE)
