#!/usr/bin/env python3
"""Contrato do overlay /fala: sem gastar voz no boot, sem atalho frouxo, com token."""

from pathlib import Path
import re
import unittest


ROOT = Path(__file__).resolve().parents[1]
FALA_JS = (ROOT / "web" / "fala.js").read_text(encoding="utf-8")
FALA_HTML = (ROOT / "web" / "fala.html").read_text(encoding="utf-8")


class FalaOverlayTest(unittest.TestCase):
    def test_boot_does_not_auto_call_speech(self):
        self.assertNotRegex(FALA_JS, r"setTimeout\(\s*\(\)\s*=>\s*speak\(")
        self.assertIn("user-gesture", FALA_JS)

    def test_sends_owner_token_when_present(self):
        self.assertIn("jarvis-owner-token-v1", FALA_JS)
        self.assertIn("X-Jarvis-Owner-Token", FALA_JS)

    def test_microphone_start_is_guarded(self):
        self.assertIn("rec.start()", FALA_JS)
        self.assertRegex(FALA_JS, r"try\s*\{[^}]*rec\.start\(\)", re.S)

    def test_does_not_open_gmail_on_any_email_mention(self):
        self.assertNotIn(r"\bgmail\b|\be-?mail\b", FALA_JS)
        self.assertIn("gmail", FALA_JS)

    def test_revokes_audio_after_playback_not_on_start(self):
        self.assertIn("ended", FALA_JS)
        self.assertNotRegex(FALA_JS, r"await audio\.play\(\);\s*URL\.revokeObjectURL")

    def test_overlay_page_is_self_contained(self):
        self.assertIn('id="orb"', FALA_HTML)
        self.assertIn("/download/mac", FALA_HTML)
        self.assertIn("creator-seal.js", FALA_HTML)
        self.assertIn('id="loginForm"', FALA_HTML)
        self.assertIn('id="accessLine"', FALA_HTML)
        self.assertIn('id="moreButton"', FALA_HTML)
        self.assertIn('id="minimizeButton"', FALA_HTML)
        self.assertIn('id="loginToggle"', FALA_HTML)
        self.assertIn('id="rememberLogin"', FALA_HTML)
        self.assertIn('id="voiceChip"', FALA_HTML)
        self.assertIn('id="buildLine"', FALA_HTML)
        self.assertIn('id="updateToast"', FALA_HTML)
        self.assertIn('id="updateReloadButton"', FALA_HTML)
        self.assertIn('id="retryButton"', FALA_HTML)
        self.assertIn('id="debugToggle"', FALA_HTML)
        self.assertIn("www.instagram.com", FALA_HTML)
        self.assertIn("jarvis-remember-login-v1", FALA_JS)
        self.assertIn('id="extras"', FALA_HTML)
        self.assertIn("jarvis-logo.png", FALA_HTML)
        self.assertIn('class="launch"', FALA_HTML)
        self.assertIn("JARVIS", FALA_HTML)
        self.assertNotIn("oi Jarvis", FALA_HTML)
        self.assertIn("web.whatsapp.com", FALA_HTML)
        self.assertIn("www.google.com", FALA_HTML)

    def test_wake_loop_listens_for_oi_jarvis(self):
        self.assertIn("startWakeLoop", FALA_JS)
        self.assertIn("keepListening", FALA_JS)
        self.assertIn("continuous = true", FALA_JS)
        self.assertIn("/login", FALA_JS)
        self.assertIn("app-mode", FALA_JS)
        self.assertIn("jarvis-fala-listen", FALA_JS)
        self.assertIn("tryAutoListen", FALA_JS)
        self.assertIn("keepArmed", FALA_JS)
        self.assertIn('name: "microphone"', FALA_JS)
        self.assertIn(r"fala", FALA_JS)
        self.assertIn("setInterval(kick, 4000)", FALA_JS)
        self.assertIn("__jarvisNativeListen", FALA_JS)
        self.assertIn("Diga Jarvis.", FALA_HTML)
        self.assertNotIn("Pode falar: oi Jarvis.", FALA_HTML)
        self.assertIn("function foldSpeech", FALA_JS)
        self.assertIn("function splitWake", FALA_JS)
        self.assertIn("jarvius", FALA_JS)
        self.assertIn("ja vis", FALA_JS)
        self.assertIn("heardLine", FALA_HTML)
        self.assertIn("reloadButton", FALA_HTML)
        self.assertIn("forceListen", FALA_JS)
        self.assertIn('nativeListen("restart")', FALA_JS)
        self.assertIn("550", FALA_JS)
        self.assertIn("postJson", FALA_JS)
        self.assertIn("open.spotify.com", FALA_JS)
        self.assertIn("calendar.google.com", FALA_JS)
        self.assertIn("localClock", FALA_JS)
        self.assertNotIn("sempre ouvindo", FALA_HTML)
        self.assertNotIn("sempre ouvindo", FALA_JS)
        self.assertIn("20260821-fit2", FALA_HTML)
        self.assertIn("grid-template-columns: 1fr 1fr", (ROOT / "web" / "fala.css").read_text(encoding="utf-8"))
        self.assertIn('class="dock"', FALA_HTML)
        self.assertIn('class="meta"', FALA_HTML)
        self.assertIn("btn-accent", FALA_HTML)
        self.assertIn("class=\"btn btn-accent\"", FALA_HTML)
        self.assertIn("sleepUntilWake", FALA_JS)
        self.assertIn('nativeListen("sleep")', FALA_JS)
        self.assertIn("wakeOnly", (ROOT / "11_SCRIPTS" / "jarvis_native_app.swift").read_text(encoding="utf-8"))
        self.assertIn("JARVIS · 3×", FALA_JS)
        self.assertIn("jarvis_3x", FALA_JS)
        self.assertIn("token:", FALA_JS)
        self.assertIn("shell?.overlay", FALA_JS)
        self.assertIn("Atualizar", FALA_HTML)
        self.assertNotIn("Reiniciar", FALA_HTML)
        self.assertIn('nativeWindow("touch")', FALA_JS)
        self.assertIn("function isLookAsk", FALA_JS)
        self.assertIn("function seeScreen", FALA_JS)
        self.assertIn("jarvisSee", FALA_JS)
        self.assertIn("__jarvisOnScreen", FALA_JS)
        self.assertIn("attachments", FALA_JS)
        self.assertIn("object-fit: contain", (ROOT / "web" / "fala.css").read_text(encoding="utf-8"))
        self.assertIn("width: 80%", (ROOT / "web" / "fala.css").read_text(encoding="utf-8"))
        self.assertIn("idle-orb", FALA_HTML)
        self.assertIn('class="booting"', FALA_HTML)
        self.assertIn('class="viz"', FALA_HTML)
        self.assertIn("Sim, senhor.", FALA_JS)
        self.assertIn("voice:down", FALA_JS)
        self.assertIn("function isRepeatAsk", FALA_JS)
        self.assertIn("toggleMeeting", FALA_JS)
        self.assertIn("needs-login", FALA_JS)
        self.assertIn("idle-orb", FALA_JS)
        self.assertIn("__jarvisSetIdle", FALA_JS)
        self.assertIn("minimizeButton", FALA_HTML)
        css = (ROOT / "web" / "fala.css").read_text(encoding="utf-8")
        self.assertIn("vizwing", css)
        self.assertIn("bootin", css)
        self.assertNotIn("@keyframes pulse", css)
        self.assertIn("168, 85, 247", css)
        self.assertIn("border-radius: 6px", css)
        self.assertIn(".btn-accent", css)
        self.assertIn("--accent: #7c3aed", css)
        self.assertIn("box-shadow: none", css)
        self.assertIn("idle-orb", css)
        self.assertIn("html:not(.armed) #heardLine", css)
        self.assertIn(".dock", css)
        self.assertIn("margin-top: auto", css)
        self.assertIn("#120c1c", css)
        self.assertIn("-webkit-app-region: drag", css)
        self.assertIn("jarvisWindow", FALA_JS)
        self.assertIn('nativeWindow("hide")', FALA_JS)
        self.assertIn('nativeWindow("touch")', FALA_JS)
        self.assertIn('nativeWindow("focus")', FALA_JS)
        self.assertIn("function spokenReply", FALA_JS)
        self.assertIn("function stopSpeak", FALA_JS)
        self.assertIn("eae", FALA_JS)
        self.assertIn("45_000", FALA_JS)
        self.assertIn("WAKE_NAME", FALA_JS)
        self.assertIn("WAKE_ONLY", FALA_JS)
        self.assertIn("function expandCommands", FALA_JS)
        self.assertIn("function looksLikeCommand", FALA_JS)
        self.assertIn("function isQuietAsk", FALA_JS)
        self.assertIn("stayQuiet", FALA_JS)
        self.assertIn("drainQueue", FALA_JS)
        self.assertIn('postMessage("stop")', FALA_JS)

    def test_does_not_spend_speech_on_greeting(self):
        self.assertNotIn("greetOnce", FALA_JS)
        self.assertNotIn("speakLocal", FALA_JS)
        self.assertNotIn("speechSynthesis", FALA_JS)
        self.assertIn("slice(0, 220)", FALA_JS)

    def test_prefers_localhost_pocket_tts_before_browser_voice(self):
        self.assertIn("JarvisLocalVoice", FALA_JS)
        self.assertIn("speakBlob", FALA_JS)
        self.assertIn("local-voice.js", FALA_HTML)
        self.assertIn("await speak(spoken)", FALA_JS)
        self.assertNotIn("speakLocal", FALA_JS)
        self.assertIn('persona', FALA_JS)
        self.assertIn("applyPersona", FALA_JS)
        self.assertIn("speaking", FALA_JS)
        self.assertIn("pesquisa no google", FALA_JS)
        self.assertIn("function resolveOpen", FALA_JS)
        self.assertIn("/\\bwhatsapp\\b/", FALA_JS)
        self.assertIn("showAnswerLink", FALA_JS)
        self.assertIn("debug=1", FALA_JS)
        self.assertIn("youtube.com/results", FALA_JS)
        self.assertIn("como chegar", FALA_JS)
        self.assertIn("clearStaleSession", FALA_JS)
        self.assertIn("mountDebug", FALA_JS)
        self.assertIn("ultron", FALA_JS)

    def test_named_spotify_is_not_a_web_shortcut(self):
        self.assertIn("function isMacSpotifyCommand", FALA_JS)
        self.assertIn(r"homem\s+de\s+ferro", FALA_JS)
        self.assertRegex(FALA_JS, r"isMacSpotifyCommand\(value\)\) return null")
        self.assertIn("open.spotify.com", FALA_JS)

    def test_speech_mutes_recognition_until_ended(self):
        self.assertIn("muteMicForSpeech", FALA_JS)
        self.assertIn("unmuteMicAfterSpeech", FALA_JS)
        self.assertIn(".finally", FALA_JS)
        self.assertRegex(FALA_JS, r"function hearSpoken\([\s\S]*if \(speaking\) \{")
        self.assertRegex(FALA_JS, r"function unmuteMicAfterSpeech\([\s\S]*keepArmed\(")
        self.assertRegex(FALA_JS, r"function startWebBackup\([\s\S]*hasNativeListen\(\)\) return")
        self.assertIn("askQueue.length >= 4", FALA_JS)
        self.assertNotRegex(FALA_JS, r"speak\(message\);\s*busy = false;\s*keepArmed")
        self.assertIn("await speak(spokenReply(message))", FALA_JS)

    def test_orb_click_does_not_permanently_disable_listen(self):
        click = re.search(r'orb\.addEventListener\("click", \(\) => \{([^}]+)\}', FALA_JS)
        self.assertIsNotNone(click)
        self.assertIn("forceListen", click.group(1))
        self.assertNotIn("stopWakeLoop", click.group(1))
        self.assertIn("Diga Jarvis.", FALA_HTML)

    def test_native_app_bridge_hooks_speak_and_listen(self):
        self.assertIn("jarvisSpeak", FALA_JS)
        self.assertIn("jarvisListen", FALA_JS)
        self.assertIn("__jarvisNativeHeard", FALA_JS)
        self.assertIn("hasNativeSpeak", FALA_JS)
        self.assertIn("hasNativeListen", FALA_JS)
        self.assertNotIn("voz na nuvem", FALA_JS)
        self.assertIn("voz JARVIS", FALA_JS)
        self.assertIn('dataset.state = "local"', FALA_JS)
        self.assertIn("SHELL_VERSION", FALA_JS)
        self.assertIn("updateToast", FALA_HTML)
        self.assertIn("Atualizar", FALA_HTML)
        self.assertIn("restartForUpdate", FALA_JS)
        self.assertIn("jarvisRestart", FALA_JS)
        self.assertIn("buildLine", FALA_HTML)
        self.assertIn("foldSpeech", FALA_JS)
        self.assertIn("paintHeard", FALA_JS)


if __name__ == "__main__":
    unittest.main(verbosity=2)
