create table if not exists public.jarvis_notes (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'theo' check (owner_id = 'theo'),
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 4000),
  source text not null default 'jarvis-web' check (char_length(source) between 1 and 80),
  mac_saved boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  archived_at timestamptz
);

create index if not exists jarvis_notes_owner_created_idx
  on public.jarvis_notes (owner_id, created_at desc)
  where archived_at is null;

alter table public.jarvis_notes enable row level security;
revoke all on table public.jarvis_notes from anon, authenticated;
revoke all on sequence public.jarvis_notes_id_seq from anon, authenticated;

comment on table public.jarvis_notes is
  'Private single-operator notepad for Theo Jarvis; server key only.';

alter table public.jarvis_device_commands
  drop constraint if exists jarvis_device_commands_action_check;

alter table public.jarvis_device_commands
  add constraint jarvis_device_commands_action_check
  check (action in (
    'open_application',
    'close_application',
    'spotify_control',
    'message_send',
    'screen_capture',
    'screen_record',
    'github_overview',
    'storage_scan',
    'system_memory',
    'self_edit',
    'save_note'
  ));
