create table if not exists public.jarvis_device_commands (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'theo' check (owner_id = 'theo'),
  action text not null
    check (action in (
      'open_application', 'close_application', 'message_send',
      'screen_capture', 'storage_scan', 'system_memory'
    )),
  target text not null default '' check (char_length(target) <= 120),
  request_text text not null check (char_length(request_text) between 1 and 8000),
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed')),
  result text not null default '' check (char_length(result) <= 8000),
  created_at timestamptz not null default timezone('utc', now()),
  claimed_at timestamptz,
  completed_at timestamptz
);

create index if not exists jarvis_device_commands_pending_idx
  on public.jarvis_device_commands (status, created_at asc)
  where status in ('pending', 'running');

create table if not exists public.jarvis_device_workers (
  worker_id text primary key check (char_length(worker_id) between 1 and 120),
  owner_id text not null default 'theo' check (owner_id = 'theo'),
  hostname text not null check (char_length(hostname) between 1 and 255),
  version text not null default '1',
  last_seen_at timestamptz not null default timezone('utc', now())
);

alter table public.jarvis_device_commands enable row level security;
alter table public.jarvis_device_workers enable row level security;

revoke all on table public.jarvis_device_commands from anon, authenticated;
revoke all on table public.jarvis_device_workers from anon, authenticated;
revoke all on sequence public.jarvis_device_commands_id_seq from anon, authenticated;

comment on table public.jarvis_device_commands is
  'Private allowlisted command queue consumed by Theo local Jarvis worker.';
comment on table public.jarvis_device_workers is
  'Private heartbeat registry for Theo local Jarvis worker.';
