create table if not exists public.jarvis_memories (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'theo' check (owner_id = 'theo'),
  kind text not null default 'learning'
    check (kind in ('learning', 'decision', 'preference', 'context')),
  content text not null check (char_length(content) between 1 and 4000),
  source text not null default 'jarvis-web',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  archived_at timestamptz
);

create index if not exists jarvis_memories_owner_created_idx
  on public.jarvis_memories (owner_id, created_at desc)
  where archived_at is null;

alter table public.jarvis_memories enable row level security;

revoke all on table public.jarvis_memories from anon, authenticated;
revoke all on sequence public.jarvis_memories_id_seq from anon, authenticated;

comment on table public.jarvis_memories is
  'Private single-operator memory for Theo Jarvis; server key only.';
