alter table public.jarvis_device_commands
  add column if not exists artifact_path text not null default '',
  add column if not exists artifact_mime text not null default '';

alter table public.jarvis_device_commands
  drop constraint if exists jarvis_device_commands_artifact_path_check;

alter table public.jarvis_device_commands
  add constraint jarvis_device_commands_artifact_path_check
  check (char_length(artifact_path) <= 500);

create table if not exists public.jarvis_contacts (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'theo' check (owner_id = 'theo'),
  alias text not null check (char_length(alias) between 1 and 80),
  display_name text not null check (char_length(display_name) between 1 and 120),
  phone text not null check (phone ~ '^[0-9]{8,15}$'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (owner_id, alias)
);

create table if not exists public.jarvis_agenda_items (
  id bigint generated by default as identity primary key,
  owner_id text not null default 'theo' check (owner_id = 'theo'),
  title text not null check (char_length(title) between 1 and 1000),
  status text not null default 'pending' check (status in ('pending', 'done', 'cancelled')),
  scheduled_for timestamptz,
  source text not null default 'jarvis-web' check (char_length(source) between 1 and 80),
  created_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz
);

create index if not exists jarvis_agenda_items_pending_idx
  on public.jarvis_agenda_items (status, created_at desc)
  where status = 'pending';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('jarvis-artifacts', 'jarvis-artifacts', false, 10485760, array['image/png'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.jarvis_contacts enable row level security;
alter table public.jarvis_agenda_items enable row level security;

revoke all on table public.jarvis_contacts from anon, authenticated;
revoke all on table public.jarvis_agenda_items from anon, authenticated;
revoke all on sequence public.jarvis_contacts_id_seq from anon, authenticated;
revoke all on sequence public.jarvis_agenda_items_id_seq from anon, authenticated;

comment on column public.jarvis_device_commands.artifact_path is
  'Private object path inside jarvis-artifacts; exposed only through short-lived signed URLs.';
comment on table public.jarvis_contacts is
  'Private single-operator contact aliases for explicit Messages.app commands.';
comment on table public.jarvis_agenda_items is
  'Private persistent agenda fallback used when no n8n webhook is configured.';
